config/routes.rb
Homestead::Engine.routes.draw do
  root 'listings#search'
  resources :listings
end

app/models/homestead/address.rb
module Homestead
  class Address < ActiveRecord::Base
    belongs_to :state

    validates_presence_of :line1
    validates_presence_of :city
    validates_presence_of :state
    validates_presence_of :postal_code

    def to_s
      name
    end

    def name
      "#{line1} #{city}, #{state}"
    end
  end
end

app/models/homestead/agent.rb
module Homestead
  class Agent < ActiveRecord::Base
    has_and_belongs_to_many :listings
    belongs_to :office
    belongs_to :status, class_name: AgentStatus

    has_attached_file :photo, styles: {medium: '300x300>'}, default_url: '/assets/homestead/image_not_found.png'

    validates_attachment_content_type :photo, content_type: ['image/jpg', 'image/jpeg', 'image/png']

    validates_presence_of :first_name
    validates_presence_of :last_name
    validates_presence_of :status

    after_initialize do
      if new_record?
        self.status = AgentStatus.where(code: 'A').first
      end
    end

    def to_s
      name
    end

    def name
      "#{first_name} #{last_name}"
    end
  end
end

app/models/homestead/agent_status.rb
module Homestead
  class AgentStatus < ActiveRecord::Base
  end
end

app/models/homestead/commercial_listing.rb
module Homestead
  class CommercialListing < Listing
    belongs_to :property, class_name: CommercialProperty
    validates_presence_of :property

    accepts_nested_attributes_for :property

    after_initialize do
      # This class always has a commercial property type.
      self.property_type = PropertyType.where(code: 'C').first
    end
  end
end

app/models/homestead/commercial_property.rb
module Homestead
  class CommercialProperty < ActiveRecord::Base

    def name
      "#{city}, #{state}"
    end
  end
end

app/models/homestead/firm.rb
module Homestead
  class Firm < ActiveRecord::Base
    validates_presence_of :name

    has_many :offices
    has_many :agents, through: :offices
    has_many :listings, through: :agents
  end
end

app/models/homestead/land_listing.rb
module Homestead
  class LandListing < Listing
    belongs_to :property, class_name: LandProperty

    validates_presence_of :property

    accepts_nested_attributes_for :property

    after_initialize do
      # This call always has a land property type
      self.property_type = PropertyType.where(code: 'L').first
    end
  end
end

app/models/homestead/land_property.rb
module Homestead
  class LandProperty < ActiveRecord::Base
    validates_presence_of :lot_size

    def name
      "#{lot_size} acres"
    end
  end
end

app/models/homestead/listing.rb
module Homestead
  class Listing < ActiveRecord::Base
    validates_presence_of :listing_number, :list_date, :status, :address,
                          :list_price, :property_type, :sub_property_type,
                          :provider

    belongs_to :address
    belongs_to :status, class_name: ListingStatus
    has_and_belongs_to_many :agents
    has_one :property_type, through: :sub_property_type
    belongs_to :sub_property_type
    belongs_to :provider, class_name: ListingProvider
    has_many :photos, class_name: ListingPhoto
    has_one :primary_photo, class_name: ListingPhoto

    accepts_nested_attributes_for :address

    after_initialize do
      if new_record?
        self.provider = ListingProvider.where(name: 'Custom').first
        self.status = ListingStatus.where(code: 'A').first
        self.list_date = DateTime.now
      end
    end

    def name
      "#{listing_number} - #{address.city}, #{address.state}" if address
    end
  end
end

app/models/homestead/listing_photo.rb
module Homestead
  class ListingPhoto < ActiveRecord::Base
    belongs_to :listing
    has_attached_file :image, styles: {medium: '300x300>'}, default_url: '/assets/homestead/image_not_found.png'
    validates_attachment_content_type :image, content_type: ['image/jpg', 'image/jpeg', 'image/png']

    def name
      image_file_name
    end
  end

end

app/models/homestead/listing_provider.rb
module Homestead
  class ListingProvider < ActiveRecord::Base
  end
end

app/models/homestead/listing_status.rb
module Homestead
  class ListingStatus < ActiveRecord::Base
    validates_presence_of :code
    validates_presence_of :name
    has_many :listings, foreign_key: :status_id
  end
end

app/models/homestead/office.rb
module Homestead
  class Office < ActiveRecord::Base
    validates_presence_of :status

    has_many :agents
    has_many :listings, through: :agents
    belongs_to :status, class_name: OfficeStatus
    belongs_to :address
    belongs_to :firm

    after_initialize do
      if new_record?
        self.status = OfficeStatus.where(name: 'Active').first
      end
    end
  end
end

app/models/homestead/office_status.rb
module Homestead
  class OfficeStatus < ActiveRecord::Base
  end
end

app/models/homestead/property_type.rb
module Homestead
  class PropertyType < ActiveRecord::Base
    validates_presence_of :code
    validates_presence_of :name
    has_one :sub_property_type, dependent: :destroy
  end
end

app/models/homestead/residential_listing.rb
module Homestead
  class ResidentialListing < Listing
    belongs_to :property, class_name: ResidentialProperty

    validates_presence_of :property

    accepts_nested_attributes_for :property

    after_initialize do
      # This class always has a residential property type.
      self.property_type = PropertyType.where(code: 'R').first
    end
  end
end

app/models/homestead/residential_property.rb
module Homestead
  class ResidentialProperty < ActiveRecord::Base
    validates_presence_of :beds, :baths

    def name
      "#{beds} bed, #{baths} bath"
    end
  end
end

app/models/homestead/state.rb
module Homestead
  class State < ActiveRecord::Base
    validates_presence_of :name, :code

    def to_s
      name
    end
  end
end

app/models/homestead/sub_property_type.rb
module Homestead
  class SubPropertyType < ActiveRecord::Base
    belongs_to :property_type, class_name: Homestead::PropertyType
  end
end

app/controllers/homestead/application_controller.rb
module Homestead
  class ApplicationController < ActionController::Base
    helper_method :property_type_options
    before_filter :search_query

    def search_query
      search_params = {'s' => 'list_price desc'}
      search_params = search_params.merge(params[:q]) if params[:q]
      @q = Listing.search(search_params)
    end

    def property_type_options
      a = Homestead::PropertyType.all.map do |t|
        [t.name, t.id]
      end
      [['Property type', '']].concat(a)
    end
  end
end

app/views/homestead/listings/_details.html.erb
<div class="listing-details">
  <% if property.has_baths %>
  <strong>Baths: </strong><span><%= property.baths %></span>
  <% end %>
  <% if property.has_beds %>
  <strong>Beds: </strong><span><%= property.beds %></span>
  <% end %>
  <% if property.has_lot_size %>
    <strong>Lot Size: </strong><span><%= property.lot_size %> acres</span>
  <% end %>
</div>

app/views/homestead/listings/index.html.erb
<h1>Real Estate</h1>

<div class="listings">
<% @listings.each do |listing| %>
  <div class="listing">
    <h2>
      <span class="price"><%= listing.list_price %></span>
    </h2>
    <% if listing.has_primary_photo %>
    <a href="<%= listing_path(listing) %>">
      <%= image_tag listing.primary_photo.image.url(:medium) %>
    </a>
    <% end %>
    <h3><%= listing.address %></h3>

    <%= render(partial: 'details', locals: {property: listing.property}) %>
    <p><%= listing.remarks %></p>
  </div>
<% end %>
</div>

app/views/homestead/listings/search.html.erb
<h1>Real Estate</h1>

app/views/homestead/listings/show.html.erb
<% @listing.photos.each do |photo| %>
  <%= image_tag photo.image.url(:medium), 'class' => 'listing-photo' %>
<% end %>

<%= render partial: 'details', locals: {property: @listing.property} %>
<p><%= @listing.remarks %></p>

app/views/homestead/shared/_search_bar.html.erb
<div class="search-bar">
<div class="container">
  <%= search_form_for @q, class: 'search-form' do |f| %>
    <ul>
      <li>
        <%= f.select :property_type_id_eq, property_type_options %>
      </li>
      <li>
        <%= f.label :list_price_gteq, '$' %>
        <%= f.number_field :list_price_gteq, placeholder: 'min', step: 10_000 %>
        to
        <%= f.label :list_price_lteq, '$' %>
        <%= f.number_field :list_price_lteq, placeholder: 'max', step: 10_000 %>
      </li>
    </ul>
    <%= f.submit 'Find properties' %>
    <ul>
      <li>
        <%= sort_link @q, :list_price, 'Price' %>
      </li>
    </ul>
  <% end %>
</div>
</div>

app/views/layouts/homestead/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Homestead</title>
  <%= stylesheet_link_tag    "homestead/application", media: "all" %>
  <%= stylesheet_link_tag    "homestead/application", media: "all" %>
  <%= javascript_include_tag "homestead/application" %>
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-theme.min.css">
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-inverse">
    <div class="container">
      <div class="navbar-header">
        <a class="navbar-brand" href="/">Homestead Demo</a>
      </div>
      <ul class="nav navbar-nav">
        <li class="active">
          <a href="/">Home</a>
        </li>
        <li>
          <a href="/About">About</a>
        </li>
      </ul>
    </div>

    <%= render 'homestead/shared/search_bar' %>
  </nav>


  <div class="container">
    <main>
      <%= yield %>
    </main>
  </div>

</body>
</html>